DROP TABLE usersettingforspecies;
DROP TABLE speciestransbylanguage;

ALTER TABLE visitlog
ADD COLUMN host VARCHAR(255);


CREATE TABLE species_translation
(
  species_id INT NOT NULL,
  language VARCHAR(5) NOT NULL,
  vernacular_name VARCHAR(255),
  PRIMARY KEY (species_id, language)
);

INSERT INTO species_translation VALUES
(73,'en','Sunflower'),
(72,'en','Snapdragon'),
(70,'en','Flax'),
(116,'en','Path'),
(115,'en','Sand'),
(79,'en','Horseradish'),
(118,'en','Clover'),
(120,'en','Petunia'),
(89,'en','Lovage'),
(88,'en','Hyssop'),
(87,'en','Hemp'),
(125,'en','Lacy phacelia'),
(85,'en','Chamomile'),
(124,'en','Sweet potato'),
(84,'en','Oregano'),
(123,'en','Raspberry'),
(83,'en','Caraway'),
(122,'en','Grapes'),
(121,'en','Tobacco'),
(99,'en','Other'),
(96,'en','Apricot'),
(94,'en','Apple'),
(47,'en','Potato'),
(46,'en','Chickpea'),
(45,'en','Pea'),
(44,'en','Tomato'),
(43,'en','Spinach'),
(15,'en','Kohlrabi'),
(13,'en','Brussels sprouts'),
(19,'en','Turnip'),
(18,'en','Swede'),
(17,'en','Cabbage'),
(21,'en','Chive'),
(20,'en','Leek'),
(29,'en','Parsnip'),
(28,'en','Carrot'),
(27,'en','Watermelon'),
(26,'en','Melon'),
(25,'en','Chard'),
(24,'en','Beetroot'),
(22,'en','Onion'),
(36,'en','Rocket'),
(35,'en','Lettuce'),
(34,'en','Radish'),
(33,'en','Rhubarb'),
(32,'en','Pumpkin'),
(31,'en','Parsley'),
(30,'en','Capsicum'),
(37,'en','Celery'),
(39,'en','Wild strawberry'),
(38,'en','Celeriac'),
(42,'en','Asparagus'),
(41,'en','Hybrid strawberry'),
(40,'en','Strawberry'),
(48,'en','Basil'),
(49,'en','Thyme'),
(53,'en','Chili'),
(52,'en','Red cabbage'),
(51,'en','Corn'),
(50,'en','Soybean'),
(59,'en','Rosemary'),
(57,'en','Comfrey'),
(56,'en','Coriander'),
(54,'en','Chinese cabbage'),
(61,'en','Borage'),
(100,'en','Lawn'),
(68,'en','Wormwood'),
(107,'en','Geranium'),
(66,'en','Garlic'),
(105,'en','Nasturtium'),
(65,'en','Catnip'),
(104,'en','Mint'),
(103,'en','Marigold'),
(63,'en','Summer savory'),
(102,'en','Concrete'),
(109,'en','Pot Marigold'),
(69,'en','Sage'),
(108,'en','Squash'),
(93,'en','Yarrow'),
(12,'en','Broccoli'),
(11,'en','Cauliflower'),
(10,'en','Onion, Red'),
(9,'en','Artichoke thistle'),
(8,'en','Cucumber'),
(7,'en','Fennel'),
(6,'en','Dill'),
(4,'en','Bean'),
(2,'en','Broadbean'),
(1,'en','Eggplant');

INSERT INTO species_translation VALUES
(124,'cs','Sladké brambory'),
(123,'cs','Malina'),
(49,'cs','Tymián'),
(48,'cs','Bazalka'),
(47,'cs','Brambor'),
(46,'cs','Cizrna'),
(45,'cs','Hrách'),
(44,'cs','Rajče'),
(43,'cs','Špenát'),
(42,'cs','Chřest'),
(41,'cs','Hybrid jahoda'),
(40,'cs','Jahoda'),
(39,'cs','Lesní jahody'),
(38,'cs','Celer bulvový'),
(37,'cs','Celer'),
(36,'cs','Roketa setá'),
(35,'cs','Salát'),
(99,'cs','Ostatní'),
(34,'cs','ředkev'),
(33,'cs','Rebarbora'),
(97,'cs','Zimní ředkev'),
(32,'cs','Dýně'),
(96,'cs','Meruňka'),
(31,'cs','Petržel'),
(30,'cs','Papriky'),
(94,'cs','Jablko'),
(93,'cs','Řebříček obecný'),
(91,'cs','Pelyněk brotan'),
(9,'cs','Artyčok kardový'),
(8,'cs','Okurka'),
(7,'cs','Fenykl'),
(6,'cs','kopr'),
(5,'cs','Fazole černé oko'),
(4,'cs','Fazole'),
(3,'cs','Fazol šarlatový'),
(2,'cs','Bob obecný'),
(1,'cs','Lilek'),
(29,'cs','Petržel'),
(28,'cs','Mrkev'),
(27,'cs','Meloun vodní'),
(26,'cs','Meloun'),
(25,'cs','Mangold'),
(89,'cs','Libeček'),
(24,'cs','Řepa červená'),
(88,'cs','Yzop lékařský'),
(23,'cs','Cibule zimní'),
(87,'cs','Konopí seté'),
(22,'cs','Cibule'),
(86,'cs','Kerblík třebule'),
(21,'cs','Pažitka pobřežní'),
(20,'cs','Pór zahradní'),
(85,'cs','Heřmánek pravý'),
(84,'cs','Dobromysl obecná'),
(83,'cs','Kmín kořenný'),
(82,'cs','Vratič obecný'),
(81,'cs','Pohanka obecná'),
(109,'cs','Měsíček lékařský'),
(108,'cs','Dýně'),
(107,'cs','Pelargónie'),
(105,'cs','Lichořeřišnice'),
(104,'cs','Máta'),
(103,'cs','Aksamitník'),
(102,'cs','Beton'),
(19,'cs','Vodnice'),
(101,'cs','Záhon'),
(18,'cs','Tuřín'),
(100,'cs','Trávník'),
(17,'cs','Zelí'),
(16,'cs','Hlávková kapusta'),
(15,'cs','Kedluben'),
(14,'cs','Kapusta'),
(79,'cs','Křen selský'),
(13,'cs','Růžičková kapusta'),
(12,'cs','Brokolice'),
(11,'cs','Květák'),
(76,'cs','Pelyněk estragon'),
(10,'cs','Cibule, červená'),
(75,'cs','Merlík bílý'),
(73,'cs','Slunečnice roční'),
(72,'cs','Hledík'),
(70,'cs','Len setý'),
(69,'cs','Šalvěj'),
(68,'cs','Pelyněk'),
(66,'cs','Česnek kuchyňský'),
(65,'cs','Šanta kočičí'),
(63,'cs','Saturejka zahradní'),
(61,'cs','Brutnák lékařský'),
(59,'cs','Rozmarýn lékařský'),
(57,'cs','Kostivalová'),
(56,'cs','Koriandr setý'),
(54,'cs','Čínské zelí'),
(53,'cs','Chilli paprička'),
(52,'cs','Červené zelí'),
(51,'cs','Kukuřice setá'),
(50,'cs','Sója'),
(116,'cs','Chodník'),
(115,'cs','Písek'),
(118,'cs','Jetel'),
(120,'cs','Petunie'),
(121,'cs','Tabák'),
(122,'cs','Réva'),
(125,'cs','Svazenka vratičolistá');

INSERT INTO species_translation VALUES
(73,'de','Sonnenblume'),
(72,'de','Löwenmäuler'),
(70,'de','Gemeiner Lein'),
(116,'de','Weg'),
(115,'de','Sand'),
(79,'de','Meerrettich'),
(118,'de','Klee'),
(120,'de','Petunien'),
(89,'de','Liebstöckel'),
(88,'de','Ysop'),
(87,'de','Nutzhanf'),
(125,'de','Rainfarn-Phazelie'),
(85,'de','Kamille'),
(124,'de','Süßkartoffel'),
(84,'de','Oregano'),
(123,'de','Himbeere'),
(83,'de','Kümmel'),
(122,'de','Weinrebe'),
(121,'de','Tabak'),
(99,'de','Andere'),
(96,'de','Aprikose'),
(94,'de','Apfel'),
(47,'de','Kartoffel'),
(46,'de','Kichererbse'),
(45,'de','Erbse'),
(44,'de','Tomate'),
(43,'de','Spinat'),
(15,'de','Kohlrabi'),
(13,'de','Rosenkohl'),
(19,'de','Speiserübe'),
(18,'de','Steckrübe'),
(17,'de','Weißkohl'),
(21,'de','Schnittlauch'),
(20,'de','Lauch'),
(29,'de','Pastinak'),
(28,'de','Karotte'),
(27,'de','Wassermelone'),
(26,'de','Melone'),
(25,'de','Mangold'),
(24,'de','Rote Bete'),
(22,'de','Zwiebel'),
(36,'de','Senfrauke'),
(35,'de','Salat'),
(34,'de','Rettich'),
(33,'de','Rhabarber'),
(32,'de','Kürbisse'),
(31,'de','Petersilie'),
(30,'de','Paprika'),
(37,'de','Sellerie'),
(39,'de','Wald-Erdbeere'),
(38,'de','Knollensellerie'),
(42,'de','Spargel'),
(41,'de','Erdbeere mix Wald-Erdbeere'),
(40,'de','Erdbeere'),
(48,'de','Basilikum'),
(49,'de','Thymian'),
(53,'de','Spanischer Pfeffer'),
(52,'de','Rotkohl'),
(51,'de','Mais'),
(50,'de','Sojabohne'),
(59,'de','Rosmarin'),
(57,'de','Beinwell'),
(56,'de','Koriander'),
(54,'de','Chinakohl'),
(61,'de','Borretsch'),
(100,'de','Rasen'),
(68,'de','Wermutkraut'),
(107,'de','Pelargonien'),
(66,'de','Knoblauch'),
(105,'de','Große Kapuzinerkresse'),
(65,'de','Katzenminze'),
(104,'de','Minzen'),
(103,'de','Tagetes'),
(63,'de','Sommer-Bohnenkraut'),
(102,'de','Beton'),
(109,'de','Ringelblume'),
(69,'de','Salbei'),
(108,'de','Kürbis'),
(93,'de','Gemeine Schafgarbe'),
(12,'de','Broccoli'),
(11,'de','Blumenkohl'),
(10,'de','Zwiebel Rote'),
(9,'de','Artischocke'),
(8,'de','Gurke'),
(7,'de','Fenchel'),
(6,'de','Dill'),
(4,'de','Bohne'),
(2,'de','Ackerbohne'),
(1,'de','Aubergine');

INSERT INTO species_translation VALUES
(1,'en_UK','Aubergine'),
(30,'en_UK','Sweet pepper'),
(65,'en_UK','Cat mint'),
(51,'en_UK','Maize'),
(108,'en_UK','Marrows');

INSERT INTO species_translation VALUES
(1,'en_US','Eggplant'),
(30,'en_US','Bell pepper'),
(19,'en_US','Turnip'),
(18,'en_US','Rutabaga'),
(53,'en_US','Chili pepper');

INSERT INTO species_translation VALUES
(124,'es','Batata'),
(123,'es','Frambuesa'),
(49,'es','Tomillo'),
(48,'es','Albahaca'),
(47,'es','Patata'),
(46,'es','Garbanzo'),
(45,'es','Arvejo'),
(44,'es','Tomate'),
(43,'es','Espinaca'),
(42,'es','Espárrago'),
(41,'es','Fresón'),
(40,'es','Fresa'),
(39,'es','Fresa salvaje'),
(38,'es','Apio nabo'),
(37,'es','Apio'),
(36,'es','Rúcula'),
(35,'es','Lechuga'),
(99,'es','Otro'),
(34,'es','Rábano'),
(33,'es','Ruibarbo'),
(97,'es','Rábano de invierno'),
(32,'es','Calabaza'),
(96,'es','Albaricoque'),
(31,'es','Perejil'),
(30,'es','Pimiento morrón'),
(94,'es','Manzana'),
(93,'es','Achillea millefolium'),
(91,'es','Artemisia abrotanum'),
(9,'es','Alcachofa'),
(7,'es','Hinojo'),
(6,'es','Eneldo'),
(5,'es','Alubia carilla'),
(4,'es','Haba bean'),
(3,'es','Ayocote'),
(2,'es','Haba'),
(1,'es','Berenjena'),
(29,'es','Chirivía'),
(28,'es','Zanahoria'),
(27,'es','Sandía'),
(26,'es','Melón'),
(25,'es','Acelga'),
(89,'es','Levístico'),
(24,'es','Remolacha '),
(88,'es','Hisopo'),
(23,'es','Cebolleta'),
(87,'es','Cáñamo'),
(22,'es','Cebolla'),
(86,'es','Perifollo'),
(21,'es','Cebollino'),
(20,'es','Puerro'),
(85,'es','Manzanilla'),
(84,'es','Orégano'),
(83,'es','Alcaravea'),
(82,'es','Tanaceto'),
(81,'es','Alforfón'),
(109,'es','Caléndula'),
(108,'es','Calabacín'),
(107,'es','Geranio'),
(105,'es','Nasturtium'),
(104,'es','Menta'),
(103,'es','Margarita'),
(102,'es','Hormigón'),
(19,'es','Nabo'),
(101,'es','Límite'),
(18,'es','Nabicol'),
(100,'es','Césped'),
(17,'es','Repollo'),
(16,'es','Col rizada'),
(15,'es','Colirrábano'),
(14,'es','Berza'),
(79,'es','Rábano picante'),
(13,'es','Coles de Bruselas'),
(12,'es','Brócoli '),
(11,'es','Coliflor'),
(76,'es','Estragón'),
(10,'es','Cebolla roja'),
(75,'es','Chenopodium album'),
(73,'es','Girasol'),
(72,'es','Antirrhinum'),
(70,'es','Lino'),
(69,'es','Salvia'),
(68,'es','Artemisia'),
(66,'es','Ajo'),
(65,'es','Gatera'),
(63,'es','Ajedrea de jardín'),
(61,'es','Borraja'),
(59,'es','Romero'),
(57,'es','Consuelda'),
(56,'es','Cilantro'),
(54,'es','Col china'),
(53,'es','Pimiento Chile'),
(52,'es','Lombarda'),
(51,'es','Maíz'),
(50,'es','Soja'),
(116,'es','Camino'),
(115,'es','Arena'),
(118,'es','Trébol'),
(120,'es','Petunia'),
(121,'es','Tabaco'),
(122,'es','Uvas'),
(125,'es','Phacelia Tanacetifolia');

INSERT INTO species_translation VALUES
(124,'fr','Patates douce'),
(123,'fr','Framboises'),
(49,'fr','Thym'),
(48,'fr','Basilic'),
(47,'fr','Pomme de terre'),
(46,'fr','Pois chiche'),
(45,'fr','Pois'),
(44,'fr','Tomates'),
(43,'fr','Epinards'),
(42,'fr','Asperges'),
(41,'fr','Fraises hybride'),
(40,'fr','Fraises'),
(39,'fr','Fraises des bois'),
(38,'fr','Céleris-rave'),
(37,'fr','Céleris'),
(36,'fr','Rocket'),
(35,'fr','Laitues'),
(99,'fr','Autre'),
(34,'fr','Radis'),
(33,'fr','Rhubarbe'),
(97,'fr','Radis d''hiver'),
(32,'fr','Citrouilles'),
(96,'fr','Abricots'),
(31,'fr','Persil'),
(30,'fr','Poivrons'),
(94,'fr','Pommes'),
(93,'fr','Achillée'),
(91,'fr','Aurone'),
(9,'fr','Artichaut'),
(8,'fr','Concombres'),
(7,'fr','Fenouil'),
(6,'fr','Aneth'),
(5,'fr','Haricots à œil noir'),
(4,'fr','Haricots'),
(3,'fr','Haricot d''Espagne'),
(2,'fr','Fèves'),
(1,'fr','Aubergines'),
(29,'fr','Panais'),
(28,'fr','Carottes'),
(27,'fr','Pastèque'),
(26,'fr','Melon'),
(25,'fr','Bettes'),
(89,'fr','Livèche'),
(24,'fr','Betterave'),
(88,'fr','Hysope'),
(23,'fr','Ciboule'),
(87,'fr','Chanvre'),
(22,'fr','Oignon'),
(86,'fr','Cerfeuil'),
(21,'fr','Ciboulette'),
(20,'fr','Poireau'),
(85,'fr','Camomille'),
(84,'fr','Oregan'),
(83,'fr','Cumin'),
(82,'fr','Chrysantheme'),
(81,'fr','Sarrasin'),
(109,'fr','Calendula'),
(108,'fr','Courge'),
(107,'fr','Gerranium'),
(105,'fr','Capucine'),
(104,'fr','Menthe'),
(103,'fr','Souci'),
(102,'fr','Concrete'),
(19,'fr','Navet'),
(101,'fr','Bordure'),
(18,'fr','Rutabaga'),
(100,'fr','Pelouse'),
(17,'fr','Chou'),
(16,'fr','Chou de Savoie'),
(15,'fr','Chou-rave'),
(14,'fr','Chou frisé'),
(79,'fr','Raifort'),
(13,'fr','Choux de Bruxelles'),
(12,'fr','Broccoli'),
(11,'fr','Chou Fleu'),
(76,'fr','Estragon'),
(10,'fr','Oignon Rouge'),
(75,'fr','Chénopode blanc'),
(73,'fr','Tournesol'),
(72,'fr','Muflier gueule de loup'),
(70,'fr','Lin'),
(69,'fr','Sauge'),
(68,'fr','Armoise'),
(66,'fr','Ail'),
(65,'fr','Nepeta'),
(63,'fr','Sarriette'),
(61,'fr','Bourrache'),
(59,'fr','Rosemary'),
(57,'fr','Consoude'),
(56,'fr','Coriandre'),
(54,'fr','Chou Chinois'),
(53,'fr','Piment'),
(52,'fr','Chou rouge'),
(51,'fr','Maïs'),
(50,'fr','Soja'),
(116,'fr','Chemin'),
(115,'fr','Sable'),
(118,'fr','Treffle'),
(120,'fr','Petunia'),
(121,'fr','Tabac'),
(122,'fr','Raisin'),
(125,'fr','Phacélie');

INSERT INTO species_translation VALUES
(12,'ro','Broccoli'),
(11,'ro','Conopidă'),
(10,'ro','Ceapă roşie'),
(9,'ro','Cardon'),
(8,'ro','Castravete'),
(89,'ro','Leuştean'),
(88,'ro','Isop'),
(87,'ro','Cânepă'),
(86,'ro','Hasmaţuchi'),
(125,'ro','Facelia'),
(85,'ro','Muşeţel'),
(124,'ro','Cartof dulce'),
(109,'ro','Gălbenele'),
(69,'ro','Salvie'),
(108,'ro','Dovlecel'),
(70,'ro','In'),
(72,'ro','Gura leului'),
(73,'ro','Floare soarelui'),
(75,'ro','Talpa gâştei - albă'),
(116,'ro','Potecă'),
(76,'ro','Tarhon'),
(115,'ro','Nisip'),
(79,'ro','Hrean'),
(118,'ro','Trifoi'),
(81,'ro','Hrişcă'),
(120,'ro','Petunie'),
(84,'ro','Oregano'),
(123,'ro','Zmeură'),
(83,'ro','Chimen'),
(122,'ro','Viţă de vie'),
(82,'ro','Vetrice'),
(121,'ro','Tutun'),
(99,'ro','Altceva'),
(97,'ro','Ridiche de iarnă'),
(59,'ro','Rozmarin'),
(57,'ro','Tătăneasă'),
(56,'ro','Coriandru'),
(54,'ro','Varză chinezească'),
(101,'ro','Bordură'),
(61,'ro','Limba mielului'),
(100,'ro','Pajişte'),
(68,'ro','Pelin'),
(107,'ro','Muşcată'),
(66,'ro','Usturoi'),
(105,'ro','Condurul doamnei'),
(65,'ro','Iarba mâţei'),
(104,'ro','Mentă'),
(103,'ro','Gălbenele'),
(39,'ro','Căpşuni sălbatice'),
(38,'ro','Ţelină de rădăcină'),
(37,'ro','Ţelină'),
(36,'ro','Voinicică'),
(35,'ro','Salată'),
(34,'ro','Ridiche'),
(33,'ro','Revent'),
(32,'ro','Bostan'),
(31,'ro','Pătrunjel'),
(30,'ro','Ardei gras'),
(29,'ro','Păstârnac'),
(28,'ro','Morcov'),
(27,'ro','Pepene'),
(26,'ro','Pepene galben'),
(25,'ro','Mangold'),
(24,'ro','Sfeclă'),
(23,'ro','Ceapă lungă'),
(22,'ro','Ceapă'),
(21,'ro','Arpagic'),
(20,'ro','Praz'),
(19,'ro','Nap'),
(18,'ro','Nap porcesc'),
(17,'ro','Varză'),
(16,'ro','Varză creaţă'),
(15,'ro','Gulie'),
(14,'ro','Varză decorativă'),
(13,'ro','Varză de Bruxelles'),
(63,'ro','Cimbru'),
(102,'ro','Beton'),
(96,'ro','Caisă'),
(94,'ro','Măr'),
(93,'ro','Coada şoricelului'),
(91,'ro','Lemnul domnului'),
(7,'ro','Fenicul'),
(49,'ro','Cimbru de câmp'),
(48,'ro','Busuioc'),
(47,'ro','Cartof'),
(46,'ro','Năut'),
(45,'ro','Mazăre'),
(44,'ro','Roşie'),
(43,'ro','Spanac'),
(42,'ro','Sparanghel'),
(41,'ro','Căpşuni hibrid'),
(40,'ro','Căpşuni'),
(53,'ro','Ardei iute'),
(52,'ro','Varză roşie'),
(51,'ro','Porumb'),
(50,'ro','Soia'),
(6,'ro','Mărar'),
(5,'ro','Fasole ochi negri'),
(3,'ro','Fasole de spania'),
(4,'ro','Fasole'),
(2,'ro','Bob'),
(1,'ro','Vânătă');

INSERT INTO species_translation VALUES
(12,'sv','Broccoli'),
(11,'sv','Blomkål'),
(68,'sv','Malört'),
(107,'sv','Pelargon'),
(66,'sv','Vitlök'),
(105,'sv','Indiankrasse'),
(65,'sv','Kattmynta'),
(104,'sv','Mint'),
(103,'sv','Tagetes'),
(63,'sv','Sommarkyndel'),
(102,'sv','Betong'),
(109,'sv','Ringbloma'),
(69,'sv','Kryddsalvia'),
(108,'sv','Zucchini'),
(73,'sv','Solros'),
(72,'sv','Lejongap'),
(70,'sv','Lin'),
(116,'sv','Gång'),
(115,'sv','Sand'),
(79,'sv','Pepparrot'),
(118,'sv','Klöver'),
(120,'sv','Petunia'),
(89,'sv','Libbsticka'),
(88,'sv','Isop'),
(87,'sv','Hampa'),
(125,'sv','Honungsfacelia'),
(85,'sv','Kamomill'),
(124,'sv','Sötpotatis'),
(84,'sv','Oregano'),
(123,'sv','Hallon'),
(122,'sv','Vindruvor'),
(121,'sv','Tobak'),
(10,'sv','Rödlök'),
(9,'sv','Kronärtskocka'),
(8,'sv','Gurka'),
(7,'sv','Fänkål'),
(6,'sv','Dill'),
(4,'sv','Bönor'),
(2,'sv','Bondbönor'),
(53,'sv','Chili'),
(51,'sv','Majs'),
(50,'sv','Sojabönor'),
(59,'sv','Rosmarin'),
(57,'sv','Vallört'),
(54,'sv','Kinakål'),
(61,'sv','Gurkört'),
(100,'sv','Gräsmatta'),
(99,'sv','Annan'),
(94,'sv','Äppleträd'),
(93,'sv','Röllika'),
(1,'sv','Aubergine'),
(49,'sv','Timjan'),
(48,'sv','Basilika'),
(47,'sv','Potatis'),
(45,'sv','Ärtor'),
(44,'sv','Tomat'),
(43,'sv','Spenat'),
(42,'sv','Sparris'),
(39,'sv','Smultorn'),
(38,'sv','Rotselleri'),
(37,'sv','Selleri'),
(36,'sv','Ruccola'),
(35,'sv','Sallat'),
(34,'sv','Rädisa'),
(33,'sv','Rabarber'),
(32,'sv','Pumpa'),
(31,'sv','Persilja'),
(30,'sv','Paprika'),
(29,'sv','Palsternacka'),
(28,'sv','Morot'),
(27,'sv','Vattenmelon'),
(26,'sv','Melon'),
(25,'sv','Mangold'),
(24,'sv','Rödbeta'),
(22,'sv','Lök'),
(21,'sv','Gräslök'),
(20,'sv','Purjolök'),
(19,'sv','Majrova'),
(15,'sv','Kålrabbi'),
(13,'sv','Brusselkål'),
(18,'sv','Kålrot'),
(17,'sv','Kål'),
(40,'sv','Jordgubbar');